version: 2.1
orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/' >> ~/.circlerc

      - run:
          name: Grant execution permissions to Gradle wrapper
          command: chmod +x gradlew

      - run:
          name: Run unit tests with JaCoCo
          command: ./gradlew testDebugUnitTest jacocoTestReport

      - run:
          name: Build debug APK
          command: ./gradlew assembleDebug

      - run:
          name: Run instrumented tests and gather coverage data
          command: |
            adb wait-for-device
            ./gradlew connectedAndroidTest
            adb pull /sdcard/Android/data/com.picpay.desafio.android/files/coverage.ec app/build/outputs/code-coverage/connected/

      - run:
          name: Generate JaCoCo Report for Instrumented Tests
          command: ./gradlew jacocoTestReport

      - store_test_results:
          path: app/build/reports/jacoco/jacocoTestReport

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: debugApk
