version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run:
          name: Install JDK and set JAVA_HOME
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/' >> ~/.circlerc

      - run:
          name: Grant execution permission to Gradle wrapper
          command: chmod +x gradlew

      - run:
          name: Set up Android emulator with Google APIs and GPU
          command: |
            sdkmanager "system-images;android-30;google_apis;x86_64"
            echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d pixel
            emulator -avd test -no-window -gpu swiftshader_indirect -no-audio -writable-system &

      - run:
          name: Wait for emulator to start
          command: |
            adb wait-for-device
            until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
              echo "Waiting for emulator to fully boot..."
              sleep 5
            done
            adb shell wm dismiss-keyguard
            sleep 90 # Aguarde tempo suficiente para a inicialização completa do emulador

      - run:
          name: Run instrumented tests
          command: ./gradlew connectedAndroidTest
      - store_test_results:
          path: app/build/outputs/androidTest-results

      - run:
          name: Run unit tests
          command: ./gradlew testReleaseUnitTest
      - store_test_results:
          path: app/build/test-results/testReleaseUnitTest

      - run:
          name: Build debug APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: debugApk
